### ISSUE TITLE
Inifinite Navigation Waypoints

### ISSUE THREAD

**Issue by Ryangupta8** [ut-amrl/graph_navigation#2]
I am on the unitree branch of graph_navigation, where the only changes I have made are to use GoToCallback instead of GoToCallbackPS. 
In addition I am using the laikago branch of enml and the unitree_bots branch of vector_display. Similarly, the only changes to these are to ensure the topic names & msg type for /intialpose and /move_base_simple/goal line up. 

I believe have made no structural change to any of the three repos from when I branched from master. 

// .mkv video
https://drive.google.com/file/d/1z3dj-Q0sxPkA5x1JaGEY01vGgbdRcKCc/view?usp=sharing
// .bag file corresp. to video
https://drive.google.com/file/d/1B8OUGzG77HWyu5107C4f9wD877zjH4g6/view?usp=sharing

**Comment by kvsikand** [comment]
Turns out this was an issue with some code changed in vector_display, around message types.
