### ISSUE TITLE
Missing amrl_msgs files in social_nav branch

### ISSUE THREAD

**Issue by Parv-Maheshwari** [ut-amrl/graph_navigation#32]
Hii. I am trying to set up the social_nav branch.

It would be really helpful if someone can guide me to find the amrl_msgs/NavStatusMsg.h and amrl_msgs/NavigationConfigMsg.h files. I couldn't find them at amrl_msgs

Please let me know of the alternatives in case these are not required anymore,

**Comment by joydeep-b** [comment]
@Parv-Maheshwari  The social nav planner has been merged into master, and it compiles with the latest version of `amrl_msgs`.
