### ISSUE TITLE
New commits lead to error

### ISSUE THREAD

**Issue by sadanand1120** [ut-amrl/graph_navigation#54]
I tried running graph nav in automata sim, and this showed up. Reverting back to state before @dom-lee's changes fixes it.
`[ERROR] [1698989835.534081881]: "base_link" passed to lookupTransform argument target_frame does not exist.`

**Comment by joydeep-b** [comment]
@dom-lee this needs a fallback if the TF tree is not being published.
@sadanand1120 Which robot faced this error? This error means there is a TF transform missing on that robot.

**Comment by sadanand1120** [comment]
@joydeep-b Oh its the automata simulator, not the robot
